### ISSUE TITLE
Proposal: Include ember-getowner-polyfill

### ISSUE THREAD

**Issue by aars** [pixelhandler/ember-jsonapi-resources#105]
Or even drop support for Ember 2.3 and document that users of older versions need to install (or create) a polyfill?

**Comment by pixelhandler** [comment]
@aars If this library drops support for `this.container` it would need a bump in the major version. I think using https://github.com/rwjblue/ember-getowner-polyfill would be fine for now. There is some code that uses `Ember.getOwner` or `this.container`. But some of the code still uses `container.lookupFactory` instead of `ownerInstance._lookupFactory`. By adding the polyfill those couple items would not result in deprecation warnings. 

I think I'd rather just fix the use of container to use getOwner with a fallback to the container if `Ember.getOwner` is not defined. The down tradeoff is that it adds branching in the code for getOwner/container but the upside is when ready for a major version bump we just remove the branching for container.

**Comment by pixelhandler** [comment]
In the next week or so I'll go through and remove all the container use in favor of `getOwner` some of the tests still use `this.container`

**Comment by pixelhandler** [comment]
Closing in favor of a 2.0 release that uses only getOwner api instead of container lookup
