### ISSUE TITLE
Support pod structure for blueprint generation

### ISSUE THREAD

**Issue by pixelhandler** [pixelhandler/ember-jsonapi-resources#16]
The resource blueprint was setup with the default file structure (not pods); will need to add support for generating the resource files using pod structure.

**Comment by pixelhandler** [comment]
@trabus if you have any ideas please let me know.

The resource generator in this project makes multiple files using `ember g resource` - model, adapter, serializer, initializer, etc. see https://github.com/pixelhandler/ember-jsonapi-resources/tree/master/blueprints/resource/files/app 

I'd like to support pods but I am wondering how to change that up. 

So I have https://github.com/pixelhandler/ember-jsonapi-resources/tree/master/blueprints/resource/files/app with all the folders I can’t replace them all with `__path__` perhaps I need a generated for each file then the resource generate calls all of them i think thats how the default resource generated works now making model  + route

**Comment by trabus** [comment]
The built in resource blueprint for ember-cli [actually does support pods out of the box](https://github.com/ember-cli/ember-cli/blob/master/tests/acceptance/pods-generate-test.js#L973), because of the way it essentially just proxy installs the blueprints it needs (rather than keeping them in the files folder).
