### ISSUE TITLE
Proposal: Change key 'resource' to 'relation' in hasOne/hasMany object param.

### ISSUE THREAD

**Issue by aars** [pixelhandler/ember-jsonapi-resources#95]
If it's still the case that the optional `{resource: 'direct-reports', type: 'employees'}` isn't documented (much/well) I want to suggest to rename the `resource` property of that object to `relation`. So:

```
Resource.extend({
  directReports: hasMany({relation: 'direct-reports', type: 'employees'}), // suggested
  // directReports: hasMany({resource: 'direct-reports', type: 'employees'}) // current
});
```

2 reasons:
1. Calling it resource is confusing since we're defining Resources all over the place, but that is not what it means in this case. 
2. The related-proxy stores this value as `relation`. Which is what we end up using internally. `meta.relation`.

Many times there isn't really a resource (either defined in terms of ember-jsonapi-resources or defined in terms of a JSONAPI url/resource to request) by this name. It is the name of the relationship a Resource has with some other Resource of a certain type. As defined by type.
To illustrate using urls:
http://api.pixelhandler.com/api/v1/supervisors/1/relationships/`resource`
vs
http://api.pixelhandler.com/api/v1/supervisors/1/relationships/`relation`
would make more sense since:
http://api.pixelhandler.com/api/v1/direct-reports does not exist. It is not a resource.

(I'll be happy to do the work for this. Including changes to docs)

**Comment by pixelhandler** [comment]
@aars yes I agree the relationship link used to fetch the resource uses a relationship name. From the spec, "related resource" is what we're talking about operating on using a "relationship link" see http://jsonapi.org/format/#document-resource-object-relationships

I am in favor with using "relation" for the argument object property with the relationship helper.

I'm also curious if the helpers should be named `toMany` and `toOne` instead of `hasMany` and `hasOne` the nomenclature here:

- http://jsonapi.org/format/#crud-updating-to-many-relationships
- http://jsonapi.org/format/#crud-updating-to-one-relationships

We could keep the `hasMany` and `hasOne` as aliases as well.

**Comment by pixelhandler** [comment]
I'd like to add this as a 2.0 item
